frase = str(input('Digite uma frase: ')).strip()
fr = frase.lower()
print('A letra A aparece {} vezes na frase.'.format(fr.count('a')))
print('A primeira letra A apareceu na posição {}'.format(fr.find('a')))
print('A última letra A apareceu na posição {}'.format(fr.rfind('a')))
